### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by nickalyn** [poggit-orphanage/ManyWorlds#5]
I have a server running from Plugpe for Pocketmine on an iPhone 7 32gb and every time I create a world it crashes Amy server and the world won’t load,so if I try to create a world server crashes,For some reason I don’t think the php flies were loaded to my server probably,Could you help me or fix this issue please also at line60

**Comment by JackMD** [comment]
You didnt provide any details on how the issue even occurred... Please correct the issue and provide details on how exactly the issue occurred. 

For side note:
This plugin is working absolutely fine with no errors what so ever.
